config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :posts do
    resources :comments
  end
  root "posts#index"

  get 'about' => 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments, dependent: :destroy 

	validates :title, presence: true
	validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))

		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts = Post.all.order('created_at ASC')
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if @post.update(params[:post].permit(:title, :body))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to root_path
	end

	private 
		def post_params
			params.require(:post).permit(:title, :body)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<p><%= comment.name %> <span style="font-size: 10px"><%= time_ago_in_words(comment.created_at) %></span></p>
<p>content: <%= comment.body %></p>

<% if user_signed_in? %>
	<button><%= link_to 'Delete', [comment.post, comment], method: :delete, data:{confirm: 'are you sure?' } %></button>
<% end %>	

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f|%>

	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :body %><br> 
		<%= f.text_area :body %>
	</p>


	<%= f.submit %>
	

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tumblr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'true' %>
    <%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css2?family=Roboto&display=swap' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'true' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div>
      <ul>
        <li><%= link_to 'Tumblr', root_path %></li>
        <li><%= link_to 'Posts', root_path %></li>
        <li><%= link_to 'About', about_path %></li>
      </ul>
      <% if !user_signed_in? %>
        <button><%= link_to 'Log In', new_user_session_path %></button>
      <% end %>
    </div>

    <div>
    <% if current_page?(root_path) %>
      <h1>Post Feed</h1>
    <% elsif current_page?(about_path)%>
      <h1>About Page</h1>
    <% else %>
      <%= link_to 'back to welcome page', root_path %>
    <% end %>
    <% if user_signed_in? %>
      <button><%= link_to 'Create a new post', new_post_path %></button>
      <button><%= link_to 'Sign Out ', destroy_user_session_path, method: :delete %></button>
    <% end %>
    </div>

    <% flash.each do |name, msg|%>
      <% content_tag [:div, msg]%>
    <% end %>
    <%= yield %> 
    </div>
    
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is about page</h1>

<p> has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in </p>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<%= @post.errors.full_messages %>
	<% end %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %>
	</p>

	<p>
		<%= f.submit %>
	</p>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit the post</h1>

<%= render 'form'%>

app/views/posts/index.html.erb
<h1>This is tumlr posts</h1>

<% @posts.each do |post| %>
<h3><%= link_to post.title, post %></h3>
<small><%= time_ago_in_words(post.created_at) %> ago</small>

<% end %>

app/views/posts/new.html.erb
<h1>Add a new post</h1>

<%= render 'form'%>

app/views/posts/show.html.erb
<h1>
	<%= @post.title %>
</h1>

<small>
	posted <%= time_ago_in_words(@post.created_at) %> ago
</small>

<p>
	<%= @post.body %>
</p>

<% if user_signed_in? %>
	<button><%= link_to 'edit', edit_post_path(@post) %></button>
	<button><%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: 'are you sure?'} %></button>
<% end %>

<h4>Comments <span><%= @post.comments.count %></span></h4>

<p><%= render @post.comments %></p>
<%= render 'comments/form' %>